name: CI (main)

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/_build.yml
    with:
      packShipCandidate: true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3

      - name: Add GitHub Package Repository source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GPR

      - name: Push to GitHub Packages
        run: dotnet nuget push **/ci/*.nupkg --source GPR --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}